create table users
(
    id       bigint generated by default as identity primary key,
    name     varchar(50),
    login    varchar(50),
    password varchar(50)
);

create table clients
(
    id   bigint generated by default as identity primary key,
    name varchar(255) NOT NULL
);

create table addresses
(
    id        bigint generated by default as identity primary key,
    address   varchar(255) NOT NULL,
    client_id bigint,
    foreign key (client_id) references clients (id) on delete cascade
);

create table phones
(
    id        bigint generated by default as identity primary key,
    number    varchar(255) NOT NULL,
    client_id bigint,
    foreign key (client_id) references clients (id) on delete cascade
);